version: '3.7'
services:
  db:
    image: bitnami/postgresql:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./volumes/postgress/data:/var/lib/postgresql/data"
    networks:
      - ${GLOBAL_NETWORK:-kafka}