version: '3.7'
services:
  db:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    restart: unless-stopped
    volumes:
      - './volumes/postgress/data:/var/lib/postgresql/data'
    ports:
      - "5432:5432"
    networks:
      - ${GLOBAL_NETWORK:-kafka}
